---
- hosts: all
  gather_facts: yes
  tasks:
    - name: determine server address
      set_fact:
        kalibro_configurations_addr: "{{ hostvars[groups.kalibro_configurations_servers[0]].ansible_default_ipv4.address }}"
        kalibro_processor_addr: "{{ hostvars[groups.kalibro_processor_servers[0]].ansible_default_ipv4.address }}"
  tags:
    - always
- hosts: all
  roles:
    - role: common
- hosts: db_servers
  roles:
    - role: ANXS.postgresql
      become: yes
      become_user: root
  tags:
    - db
- include: deploy-app.yml
  vars:
    rails_app_name: kalibro_configurations
  tags:
    - deploy
    - kalibro_configurations
- include: deploy-app.yml
  vars:
    rails_app_name: kalibro_processor
    rails_app_shared_files:
      - config/kalibro.yml
    rails_app_setup_playbooks:
      - "{{ playbook_dir }}/tasks/generate-kalibro-config.yml"
    rails_delayed_job_enable: yes
    rails_delayed_job_workers: 4
  tags:
    - deploy
    - kalibro_processor
- include: deploy-app.yml
  vars:
    rails_app_name: prezento
    rails_app_setup_playbooks:
      - "{{ playbook_dir }}/tasks/generate-kalibro-config.yml"
    rails_app_shared_files:
      - config/kalibro.yml
    rails_app_env_vars:
      RAILS_SERVE_STATIC_FILES: '1'
  tags:
    - deploy
    - prezento
