---
- name: Install basic packages
  apt: pkg={{item}} state=installed
  with_items: "{{ common_packages }}"
- name: Install unattended-upgrades package
  apt: pkg=unattended-upgrades state=installed
- name: Configure unattended-upgrades package
  copy: src={{item}} dest=/etc/apt/apt.conf.d
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades
- name: Enable unattended-upgrades service
  service: name=apt-daily.timer state=started enabled=yes
